bliss/cfdp/bin/start_cfdp_receiver.py
bliss/cfdp/bin/start_cfdp_sender.py
bliss/cfdp/cfdp.py
bliss/cfdp/exceptions.py
bliss/cfdp/machines/__init__.py
bliss/cfdp/machines/machine.py
bliss/cfdp/machines/receiver1.py
bliss/cfdp/machines/sender1.py
bliss/cfdp/mib.py
bliss/cfdp/pdu/filedata.py
bliss/cfdp/pdu/header.py
bliss/cfdp/test/cfdp_test.py
bliss/cfdp/test/pdu_test.py
config/config.yaml

- General light refactoring & code fixes
- Fix header data length field & update config for a few more params
- Update unit tests for updated header fixes
- Update cancel procedure

Issue #12 Testing + corresponding code fixes

---

README.md

Resolves #3 
- Rebrands BLISS to AIT
- Updates doc links

Issue #3 - Update README

---

readthedocs.yml
setup.py

Resolves #8
http://ait-dsn.readthedocs.io/en/latest/

Issue #8 - Publish docs to ReadTheDocs

---

setup.py

Issue #2 - Bump ait-core version and remove outdated dependency link

---

README.md

Issue #17 - Add docs build badge to README

---

bliss/sle/bin/examples/tm_downlink_example.py

Fix broken PDU imports after code restructuring. Default version number
in bind invocation to 4 instad of 4. Update stop time for data request
to encompass current time as ERT.
Resolve #22

Issue #22 - RAF example changes for version 4 support

---

bliss/sle/frames.py

Issue #24 - Fix TMFrame header bit mask issues

---

.travis.yml

Issue #19 - Add TravisCI config file

---

README.md

Issue #32 - Update README with contributing and community info

---

ait/dsn/sle/cltu.py

New method saves encode CLTU PDU to provided filename. 
Resolves #66

Issue #66 - Add save-to-file method to CLTU

---

ait/dsn/bin/ait_cfdp_mock_server.py
ait/dsn/bin/ait_cfdp_start_receiver
ait/dsn/bin/ait_cfdp_start_sender.py
doc/source/ait_cfdp.rst
doc/source/cfdp.rst
doc/source/index.rst
doc/source/installation.rst

Issue #58 - CFDP documentation

---

doc/source/ait_sle.rst
doc/source/index.rst
doc/source/sle.rst

- Added overview of SLE services AIT provides.
- Added user guide with examples for AIT SLE interfaces.

Issue #71 - Add SLE documentation

---

ait/dsn/bin/examples/rcf_api_test.py
config/config.yaml

Fix typo in SLE config; update RCF script for new config format (#87)

---

ait/dsn/sle/cltu.py
ait/dsn/sle/raf.py
ait/dsn/sle/rcf.py
config/config.yaml

SLE parameters were added to `config.yaml` and `rcf.py`, `raf.py` and `cltu.py` were updated accordingly.
FYI, I set all protocols `version` to 4 as a default. Please let me know if I should set `rcf` and `cltu` `version` to 5.

Issue #84 - Add SLE parameters to config file

---

ait/dsn/sle/cltu.py
ait/dsn/sle/raf.py
ait/dsn/sle/rcf.py
config/config.yaml

Please take care of PR #89 first before this PR
* replaced gui section to AIT-Core server section
* added ATI-Core notifications:options section

Issue #85 - Merge config files between AIT-Core and AIT-DSN

---

.gitignore
ait/dsn/bch/__init__.py
ait/dsn/bch/bch.py
ait/dsn/bch/test/__init__.py
ait/dsn/bch/test/bch_test.py
doc/source/ait.dsn.bch.bch.rst
doc/source/ait.dsn.bch.rst
doc/source/ait.dsn.bch.test.bch_test.rst
doc/source/ait.dsn.bch.test.rst
doc/source/ait.dsn.rst
setup.py

+ Integrated ASU-source BCH utility into ait/dsn/bch
+ Added unit tests for expected successful and rejected input
+ Added basic sphinx documentation for BCH and associated tests
Resolves #92

Issue #92 - Incorporate BCH code into AIT-DSN

---

readthedocs.yml

Issue #100 - Update Python version in RTD config

---

ait/dsn/sle/common.py

Issue #108 - Pull all attributes from kwargs and config

---

ait/dsn/aos/aos_deframer.py

Added aos_deframer baseline file that is currently being used to decode IRIS radio generated AOS frames and produce telemetry packets for the ASU LunaH-Map project

Added baseline AOS deframer code for LunaH-Map

---

ait/dsn/bin/examples/deframer/aos_deframer.py

Issue #113 - Relocation aos_deframer example and add header

---

setup.py

Issue #132 - Pin greenlets to 0.4.16

---

ait/dsn/proc/__init__.py
ait/dsn/proc/deframe_packet_processor.py
ait/dsn/proc/test/__init__.py
ait/dsn/proc/test/frame_generator_test.py
ait/dsn/proc/test/run_modulo_list.py
ait/dsn/sle/test/frames_test.py
doc/source/deframer_packet_processor.rst

- Created base implementation for a deframer/packet-processor for AOS and TM Transfer Frames.
- Created documentation for this Processor
- Added test scripts used to exercise the Processor

Issue #112 - Provide base implementation of deframer / packet processor

---

ait/dsn/encrypt/encrypter.py
ait/dsn/encrypt/kmc_encrypter.py
ait/dsn/encrypt/test/test_encrypt.py
ait/dsn/util/utils.py
doc/source/encryption.rst

Updates to encryption include:
- Fixed minor bugs found during configuration 
- Support external KMC property file (parse and replace embedded list)
- Debug print of returned TC object during decryption when verbosity enabled
- Updated and organized documentation, including more recent example KMC config

Issue 143: Updated release of AIT encryption support

---

ait/dsn/plugins/EncrypterPlugin.py
doc/source/encryption.rst

Add Encrypter plugin. 
Tested against SunRISE fsws.

Issue #155 Add Encrypter Plugin

---

ait/dsn/sle/common.py
ait/dsn/sle/frames.py

Fix call in frames.py to refactored hexint() and consolidate common.py to make consistent 
Fixes #160

Fix calls to refactored hexint()

---

ait/dsn/sle/common.py

This PR fixes how sockets are managed when attempting to connect to SLE services.
Instead of instantiating a single socket for potentially all hostnames, we now create a new socket for each hostname, and are sure to close it as part of error handling.
Testing documentation can be found in the original issue #163 
Fixes #163

Issue 163 - Create fresh socket for each hostname connection attempt

---

ait/dsn/plugins/create_cltu.py
ait/dsn/plugins/raf_plugin.py
ait/dsn/plugins/send_cltu.py
doc/source/ait.dsn.plugins.create_cltu.rst
doc/source/ait.dsn.plugins.raf_plugin.rst
doc/source/ait.dsn.plugins.rst
doc/source/ait.dsn.plugins.send_cltu.rst

These plugins allow a user to easily incorporate SLE services into ait-server.
These plugins were successfully used during DTF-21 testing.
Fixes #191

Issue #191 – Add SLE plugins
